apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./resources/namespace.yaml
- ./resources/deployment.yaml
- ./resources/ingress.yaml
- ./resources/origin-issuer.yaml
- ./resources/service.yaml

namespace: effect-website
